/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.rlha.twitch.gui;

import de.rlha.twitch.TwitchTVStream;
import java.awt.Color;
import java.io.IOException;
import javax.activation.MimeTypeParseException;

/**
 *
 * @author Roland
 */
public class TwitchTVAppGUI extends javax.swing.JFrame {

    /**
     * Creates new form TwitchTVAppGUI
     */
    public TwitchTVAppGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChannelName = new javax.swing.JLabel();
        tfChannelName = new javax.swing.JTextField();
        btnCheckLive = new javax.swing.JButton();
        lblStreamStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChannelName.setText("Channel name:");

        btnCheckLive.setText("Check");
        btnCheckLive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckLiveActionPerformed(evt);
            }
        });

        lblStreamStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStreamStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChannelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfChannelName, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheckLive)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChannelName)
                    .addComponent(tfChannelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckLive))
                .addGap(18, 18, 18)
                .addComponent(lblStreamStatus)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckLiveActionPerformed
        Thread thread = new Thread(() -> {
            String username = this.tfChannelName.getText();

            if (username == null || username.isEmpty()) {
                this.printErrorToStreamStatusLbl();
                return;
            }

            this.lblStreamStatus.setForeground(Color.BLACK);
            this.lblStreamStatus.setText("Checking ...");

            TwitchTVStream stream = new TwitchTVStream(username.trim());

            try {            
                if (stream.isLive()) {
                    this.lblStreamStatus.setForeground(Color.GREEN);
                    this.lblStreamStatus.setText(username + " is LIVE!");
                }
                else {
                    this.lblStreamStatus.setForeground(Color.RED);
                    this.lblStreamStatus.setText(username + " is OFFLINE!");
                }
            }
            catch (IOException | MimeTypeParseException ex) {
                this.printErrorToStreamStatusLbl();
            }
        });
        
        thread.start();
    }//GEN-LAST:event_btnCheckLiveActionPerformed

    private void printErrorToStreamStatusLbl() {
        this.lblStreamStatus.setForeground(Color.BLACK);
        this.lblStreamStatus.setText("Something went wrong...");        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitchTVAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitchTVAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitchTVAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitchTVAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitchTVAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckLive;
    private javax.swing.JLabel lblChannelName;
    private javax.swing.JLabel lblStreamStatus;
    private javax.swing.JTextField tfChannelName;
    // End of variables declaration//GEN-END:variables
}
